# CS577 - Homework 0

#### Christopher Hong

In [1]:
import numpy as np
import scipy.linalg as la

## A.

In [2]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([-1, 1, 3])

### 1.

In [3]:
# 2A - B
2 * A - B

array([-2, -1,  0])

### 2.

In [4]:
# ||A||
np.sqrt(A.T @ A)

3.7416573867739413

In [5]:
X = np.array([1, 0, 0])
A_dot_X = A.T @ X
A_norm = np.sqrt(A.T @ A)
X_norm = np.sqrt(X.T @ X)
np.arccos(A_dot_X / (A_norm * X_norm))

1.3002465638163236

### 3.

In [6]:
A / A_norm

array([0.26726124, 0.53452248, 0.80178373])

### 4.

In [7]:
Y = np.array([0, 1, 0])
Z = np.array([0, 0, 1])

A_alpha = A_dot_X / A_norm
A_beta = A.T @ Y / A_norm
A_gama = A.T @ Z / A_norm

print(A_alpha, A_beta, A_gama)

0.2672612419124244 0.5345224838248488 0.8017837257372732


### 5.

In [8]:
A.dot(B)

32

In [9]:
B.dot(A)

32

### 6.

In [10]:
np.arccos(A.dot(B) / (A_norm * np.sqrt(B.dot(B))))

0.2257261285527342

### 7.

In [11]:
np.cross(A, [0, 1, 0])

array([-3,  0,  1])

### 8.

In [12]:
np.cross(A, B)

array([-3,  6, -3])

In [13]:
np.cross(B, A)

array([ 3, -6,  3])

### 9.

In [14]:
np.cross(A, B)

array([-3,  6, -3])

### 10.

In [15]:
mat = np.stack((A, B, C), axis=1)
mat

array([[ 1,  4, -1],
       [ 2,  5,  1],
       [ 3,  6,  3]])

In [16]:
mat @ np.array([1, 2, 3])

array([ 6, 15, 24])

### 11.

In [17]:
A.T @ B

32

In [18]:
A @ B.T

32

## B.

In [19]:
A = np.array([[1, 2, 3],
              [4, -2, 3],
              [0, 5, -1]])
print(A)

[[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]


In [20]:
B = np.array([[1, 2, 1],
              [2, 1, -4],
              [3, -2, 1]])
print(B)

[[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]


In [21]:
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [-1, 1, 3]])
print(C)

[[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]


### 1.

In [22]:
# 2A - B
2 * A - B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

### 2.

In [23]:
A @ B

array([[ 14,  -2,  -4],
       [  9,   0,  15],
       [  7,   7, -21]])

In [24]:
B @ A

array([[  9,   3,   8],
       [  6, -18,  13],
       [ -5,  15,   2]])

### 3.

In [25]:
(A @ B).T

array([[ 14,   9,   7],
       [ -2,   0,   7],
       [ -4,  15, -21]])

In [26]:
B.T @ A.T

array([[ 14,   9,   7],
       [ -2,   0,   7],
       [ -4,  15, -21]])

### 4.

In [27]:
la.det(A)

55.0

In [28]:
la.det(B)

-42.0

### 5.

In [29]:
B[1,:].dot(B[2,:])

0

### 6.

In [30]:
la.inv(A)

array([[-0.23636364,  0.30909091,  0.21818182],
       [ 0.07272727, -0.01818182,  0.16363636],
       [ 0.36363636, -0.09090909, -0.18181818]])

In [31]:
la.inv(B)

array([[ 0.16666667,  0.0952381 ,  0.21428571],
       [ 0.33333333,  0.04761905, -0.14285714],
       [ 0.16666667, -0.19047619,  0.07142857]])

## C.

In [32]:
A = np.array([[1, 2],
              [3, 2]])
print(A)

[[1 2]
 [3 2]]


In [33]:
B = np.array([[2, -2],
              [-2, 5]])
print(B)

[[ 2 -2]
 [-2  5]]


### 1.

In [34]:
eigvals, eigvecs = la.eig(A)

In [35]:
eigvals

array([-1.+0.j,  4.+0.j])

In [36]:
eigvecs

array([[-0.70710678, -0.5547002 ],
       [ 0.70710678, -0.83205029]])

### 2.

In [37]:
la.inv(eigvecs) @ A @ eigvecs

array([[-1.0000000e+00, -4.4408921e-16],
       [ 0.0000000e+00,  4.0000000e+00]])

### 3.

In [38]:
eigvecs[:,0].dot(eigvecs[:,1])

-0.19611613513818388

### 4.

In [39]:
eigvals, eigvecs = la.eig(B)

In [40]:
eigvecs

array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]])

In [41]:
eigvecs[:,0].dot(eigvecs[:,1])

0.0

### 5.

Eigenvectors of B is orthogonal to each other.

## D.

In [42]:
def derivative(f, a, delta_x=0.01):
        return (f(a + delta_x) - f(a)) / delta_x

f(x) = x^2 + 3

g(x,y) = x^2 + y^2

### 1.

f'(x) = 2x + 3

f''(x) = 2

### 2.

$
\begin{align*}
\frac{\partial g}{\partial x} = 2x\\
\frac{\partial g}{\partial y} = 2y
\end{align*}
$

### 3.

$
\begin{align}
\nabla g(x,y) = [2x, 2y]
\end{align}
$

### 4.

$
\begin{align}
g(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{1}{2} (\frac{x - \mu}{\sigma})^2}
\end{align}
$